// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: hello.proto

package pyclient_goserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceGreetingClient is the client API for ServiceGreeting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceGreetingClient interface {
	SendGreeting(ctx context.Context, in *SendGreetingRequest, opts ...grpc.CallOption) (*SendGreetingResponse, error)
}

type serviceGreetingClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceGreetingClient(cc grpc.ClientConnInterface) ServiceGreetingClient {
	return &serviceGreetingClient{cc}
}

func (c *serviceGreetingClient) SendGreeting(ctx context.Context, in *SendGreetingRequest, opts ...grpc.CallOption) (*SendGreetingResponse, error) {
	out := new(SendGreetingResponse)
	err := c.cc.Invoke(ctx, "/hello.ServiceGreeting/SendGreeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceGreetingServer is the server API for ServiceGreeting service.
// All implementations must embed UnimplementedServiceGreetingServer
// for forward compatibility
type ServiceGreetingServer interface {
	SendGreeting(context.Context, *SendGreetingRequest) (*SendGreetingResponse, error)
	mustEmbedUnimplementedServiceGreetingServer()
}

// UnimplementedServiceGreetingServer must be embedded to have forward compatible implementations.
type UnimplementedServiceGreetingServer struct {
}

func (UnimplementedServiceGreetingServer) SendGreeting(context.Context, *SendGreetingRequest) (*SendGreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGreeting not implemented")
}
func (UnimplementedServiceGreetingServer) mustEmbedUnimplementedServiceGreetingServer() {}

// UnsafeServiceGreetingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceGreetingServer will
// result in compilation errors.
type UnsafeServiceGreetingServer interface {
	mustEmbedUnimplementedServiceGreetingServer()
}

func RegisterServiceGreetingServer(s grpc.ServiceRegistrar, srv ServiceGreetingServer) {
	s.RegisterService(&ServiceGreeting_ServiceDesc, srv)
}

func _ServiceGreeting_SendGreeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceGreetingServer).SendGreeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.ServiceGreeting/SendGreeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceGreetingServer).SendGreeting(ctx, req.(*SendGreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceGreeting_ServiceDesc is the grpc.ServiceDesc for ServiceGreeting service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceGreeting_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.ServiceGreeting",
	HandlerType: (*ServiceGreetingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendGreeting",
			Handler:    _ServiceGreeting_SendGreeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
