# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.proto import hello_pb2 as protos_dot_proto_dot_hello__pb2


class ServiceGreetingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendGreeting = channel.unary_unary(
                '/hello.ServiceGreeting/SendGreeting',
                request_serializer=protos_dot_proto_dot_hello__pb2.SendGreetingRequest.SerializeToString,
                response_deserializer=protos_dot_proto_dot_hello__pb2.SendGreetingResponse.FromString,
                )


class ServiceGreetingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendGreeting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceGreetingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendGreeting': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGreeting,
                    request_deserializer=protos_dot_proto_dot_hello__pb2.SendGreetingRequest.FromString,
                    response_serializer=protos_dot_proto_dot_hello__pb2.SendGreetingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.ServiceGreeting', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServiceGreeting(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendGreeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.ServiceGreeting/SendGreeting',
            protos_dot_proto_dot_hello__pb2.SendGreetingRequest.SerializeToString,
            protos_dot_proto_dot_hello__pb2.SendGreetingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
